[package]
name = "depth-anything-v2-ort"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { version = "0.25", default-features = false, features = ["jpeg", "png"] }
ndarray = "0.16"
num_cpus = "1.16.0"
ort = "2.0.0-rc.9"
